library(RODBC)
library(dplyr)
library(srvyr)
library(stringr)

rm(list = ls())
db <- odbcConnect("DB_CODEPLAN", uid=36692, pwd='5en4pq7w5p')
sqlTables(db) %>% 
  filter(TABLE_SCHEM=="pmad2018") %>%
  select(TABLE_NAME)

domicilio <- sqlQuery(db,"select * from pmad2018.domicilios_1023")

colnames(domicilio)

str_detect(colnames(domicilio),'C01')

table(domicilio$B02,useNA = "ifany")

#Atribuindo mascaras para as questões
domicilio <- domicilio %>% 
  mutate(tipo=factor(case_when(trimws(tipo)=='Tipo.1'~10,
                               trimws(tipo)=='Tipo.2'~20,
                               trimws(tipo)=='Tipo.3'~30,
                               trimws(tipo)=='Tipo.4'~40,
                               trimws(tipo)=='Tipo.5'~50,
                               trimws(tipo)=='Tipo.6'~60,
                               trimws(tipo)=='Tipo.7A'~71,
                               trimws(tipo)=='Tipo.7B'~72,
                               trimws(tipo)=='Tipo.7C'~73,
                               trimws(tipo)=='Tipo.7D'~74,
                               trimws(tipo)=='Tipo.8'~80),
                     levels = c(seq(10,60,10),71:74,80),
                     labels=c('Sim (Continuar a pesquisa)',
                              'Não (Unidade fechada)',
                              'Não (Recusa do morador)',
                              'Não (Unidade vaga)',
                              'Não (Unidade vaga devido a uso ocasional)',
                              'Não (Unidade vaga devido a construção ou reforma)',
                              'Não (Unidade não residencial)',
                              'Não (Unidade não encontrada)',
                              'Não (Unidade de uso coletivo)',
                              'Não (Terreno vazio)',
                              'Não (Outro motivo)')),
         B01=factor(case_when(trimws(B01)=='B01.1'~1,
                              trimws(B01)=='B01.2'~2,
                              trimws(B01)=='B01.3'~3),
                    levels = c(1:3),
                    labels=c('Permanente',
                             'Improvisado',
                             'Permanente em construção')),
         B02=factor(case_when(trimws(B02)=='B02.1'~1,
                              trimws(B02)=='B02.2'~2,
                              trimws(B02)=='B02.3'~3,
                              trimws(B02)=='B02.4'~4,
                              trimws(B02)=='B02.5'~5,
                              trimws(B02)=='B02.6'~6,
                              trimws(B02)=='B02.7'~7,
                              trimws(B02)=='B02.8'~8),
                    levels = c(1:8),
                    labels=c('B02.1 - Casa',
                             'B02.2 - Barraco',
                             'B02.3 - Cômodo',
                             'B02.4 - Quitinete/Estúdio',
                             'B02.5 - Flat',
                             'B02.6 - Apartamento',
                             'B02.7 - Uso misto',
                             'B02.8 - Outros')),
         B03=factor(case_when(trimws(B03)=='B03.1'~1,
                              trimws(B03)=='B03.2'~2,
                              trimws(B03)=='B03.3'~3,
                              trimws(B03)=='B03.4'~4,
                              trimws(B03)=='B03.5'~5,
                              trimws(B03)=='B03.6'~6,
                              trimws(B03)=='B03.7'~7,
                              trimws(B03)=='B03.8'~8,
                              trimws(B03)=='B03.9'~9,
                              trimws(B03)=='B03.10'~10,
                              trimws(B03)=='B03.11'~11,
                              trimws(B03)=='B03.12'~12,
                              trimws(B03)=='B03.13'~13,
                              trimws(B03)=='B03.14'~14,
                              trimws(B03)=='B03.15'~15),
                    levels = c(1:15),
                    labels=c('Próprio já pago (Quitado)',
                             'Próprio ainda pagando (Em aquisição)',
                             'Próprio em terreno não legalizado',
                             'Próprio em assentamento',
                             'Próprio em invasão',
                             'Alugado',
                             'Alugado em terreno não legalizado',
                             'Alugado em assentamento',
                             'Alugado em invasão',
                             'Cedido',
                             'Cedido em terreno não legalizado',
                             'Cedido em assentamento',
                             'Cedido em invasão',
                             'Funcional','Outros')),
         B04=as.numeric(case_when(trimws(B0477777)=='B04.77777'~77777,
                                  trimws(B0488888)=='B04.88888'~88888,
                                  B041>=0~B041)),
         B05=as.numeric(case_when(trimws(B0577777)=='B05.77777'~77777,
                                  trimws(B0588888)=='B05.88888'~88888,
                                  B051>=0~B051)),
         B06=factor(case_when(trimws(B06)=='B06.0'~0,
                              trimws(B06)=='B06.1'~1,
                              trimws(B06)=='B06.2'~2,
                              trimws(B06)=='B06.3'~3,
                              trimws(B06)=='B06.4'~4,
                              trimws(B06)=='B06.5'~5,
                              trimws(B06)=='B06.6'~6,
                              trimws(B06)=='B06.7'~7),
                    levels = c(0:7),
                    labels = c('Não tem imóvel próprio (Reside em um alugado, cedido ou funcional)',
                               'Escritura definitiva',
                               'Concessão de uso',
                               'Contrato de financiamento particular',
                               'Contrato de financiamento governamental',
                               'Contrato de compra e venda (Cessão de Direito)',
                               'Minha casa minha vida',
                               'Outros')),
         B07=as.numeric(B07nComodos),
         B08=as.numeric(B08nDormitorios),
         B09=as.numeric(B09nBanheiros),
         B10=factor(case_when(trimws(B10)=='B10.1'~1,
                              trimws(B10)=='B10.2'~2,
                              trimws(B10)=='B10.3'~3,
                              trimws(B10)=='B10.4'~4),
                    levels = c(1:4),
                    labels = c('Rede Geral',
                               'Poço/Cisterna',
                               'Poço Artesiano',
                               'Outros')),
         B11=factor(case_when(trimws(B11)=='B11.1'~1,
                              trimws(B11)=='B11.2'~2,
                              trimws(B11)=='B11.3'~3,
                              trimws(B11)=='B11.4'~4,
                              trimws(B11)=='B11.5'~5),
                    levels = c(1:5),
                    labels = c( 'Não tem filtro',
                                'Filtro de barro',
                                'Filtro de parede',
                                'Filtro de carvão ativado',
                                'Água Mineral')),
         B12=factor(case_when(trimws(B12)=='B12.1'~1,
                              trimws(B12)=='B12.2'~2,
                              trimws(B12)=='B12.3'~3,
                              trimws(B12)=='B12.8'~8),
                    levels = c(1:3,8),
                    labels = c('Não',
                               'Sim',
                               'Não conta com Rede Geral',
                               'Não sabe/não quis responder')),
         B13=factor(case_when(trimws(B13)=='B13.1'~1,
                              trimws(B13)=='B13.2'~2,
                              trimws(B13)=='B13.3'~3,
                              trimws(B13)=='B13.4'~4,
                              trimws(B13)=='B13.8'~8),
                    levels = c(1:4,8),
                    labels = c( 'Não',
                                'Raramente',
                                'Frequentemente',
                                'Não conta com Rede Geral',
                                'Não sabe/não quis responder')),
         B14=factor(case_when(trimws(B14)=='B14.1'~1,
                              trimws(B14)=='B14.2'~2,
                              trimws(B14)=='B14.3'~3,
                              trimws(B14)=='B14.4'~4),
                    levels = c(1:4),
                    labels = c('Rede Geral',
                               'Próprio (gerador e bateria)',
                               'Gambiarra',
                               'Outros')),
         B15=factor(case_when(trimws(B15)=='B15.1'~1,
                              trimws(B15)=='B15.2'~2,
                              trimws(B15)=='B15.3'~3,
                              trimws(B15)=='B15.8'~8),
                    levels = c(1:3,8),
                    labels = c( 'Não',
                                'Sim',
                                'Não conta com Rede Geral',
                                'Não sabe/não quis responder')),
         B16=factor(case_when(trimws(B16)=='B16.1'~1,
                              trimws(B16)=='B16.2'~2,
                              trimws(B16)=='B16.3'~3,
                              trimws(B16)=='B16.4'~4,
                              trimws(B16)=='B16.8'~8),
                    levels = c(1:4,8),
                    labels = c( 'Não',
                                'Raramente',
                                'Frequentemente',
                                'Não conta com Rede Geral',
                                'Não sabe/não quis responder')),
         B17=factor(case_when(trimws(B17)=='B17.1'~1,
                              trimws(B17)=='B17.2'~2,
                              trimws(B17)=='B17.3'~3,
                              trimws(B17)=='B17.4'~4,
                              trimws(B17)=='B17.5'~5),
                    levels = c(1:5),
                    labels = c('Rede Geral',
                               'Fossa Séptica',
                               'Fossa Rudimentar',
                               'Esgoto a céu aberto',
                               'Outros')),
         B18=factor(case_when(trimws(B18)=='B18.1'~1,
                              trimws(B18)=='B18.2'~2,
                              trimws(B18)=='B18.3'~3,
                              trimws(B18)=='B18.4'~4),
                    levels = c(1:4),
                    labels = c( 'Sem coleta seletiva',
                                'Com coleta seletiva',
                                'Jogado em local impróprio',
                                'Outro destino')),
         B190=factor(case_when(str_detect(B19,"B19.0")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B191=factor(case_when(str_detect(B19,"B19.1")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B192=factor(case_when(str_detect(B19,"B19.2")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B193=factor(case_when(str_detect(B19,"B19.3")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B194=factor(case_when(str_detect(B19,"B19.4")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B195=factor(case_when(str_detect(B19,"B19.5")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B200=factor(case_when(str_detect(B20,"B20.0")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B201=factor(case_when(str_detect(B20,"B20.1")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B202=factor(case_when(str_detect(B20,"B20.2")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B203=factor(case_when(str_detect(B20,"B20.3")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B204=factor(case_when(str_detect(B20,"B20.4")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B205=factor(case_when(str_detect(B20,"B20.5")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B206=factor(case_when(str_detect(B20,"B20.6")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         
         B210=factor(case_when(str_detect(B21,"B21.0")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B211=factor(case_when(str_detect(B21,"B21.1")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B212=factor(case_when(str_detect(B21,"B21.2")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B213=factor(case_when(str_detect(B21,"B21.3")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B214=factor(case_when(str_detect(B21,"B21.4")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B215=factor(case_when(str_detect(B21,"B21.5")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B216=factor(case_when(str_detect(B21,"B21.6")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B217=factor(case_when(str_detect(B21,"B21.7")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B218=factor(case_when(str_detect(B21,"B21.8")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         
         B220=factor(case_when(str_detect(B22,"B22.0")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B221=factor(case_when(str_detect(B22,"B22.1")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B222=factor(case_when(str_detect(B22,"B22.2")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B223=factor(case_when(str_detect(B22,"B22.3")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B224=factor(case_when(str_detect(B22,"B22.4")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B225=factor(case_when(str_detect(B22,"B22.5")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B228=factor(case_when(str_detect(B22,"B22.8")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         
         B230=factor(case_when(str_detect(B23,"B23.0")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B231=factor(case_when(str_detect(B23,"B23.1")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B232=factor(case_when(str_detect(B23,"B23.2")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B233=factor(case_when(str_detect(B23,"B23.3")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B234=factor(case_when(str_detect(B23,"B23.4")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         B238=factor(case_when(str_detect(B23,"B23.8")~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         
         C010=factor(case_when(trimws(C010)=='C01.0'~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         
         C011=as.numeric(C011),
         C012=as.numeric(C012),
         C013=as.numeric(C013),
         C014=as.numeric(C014),
         #C015=as.numeric(C015),
         C016=as.numeric(C016),
         C017=as.numeric(C017),
         #C018=as.numeric(C018),
         C019=as.numeric(C019),
         
         #C020=as.numeric(case_when(trimws(C020)=='C02.0'~1,TRUE~0),
         #labels = c('Não','Sim')),
         
         C021=as.numeric(C021),
         C022=as.numeric(C022),
         C023=as.numeric(C023),
         
         C030=factor(case_when(trimws(C030)=='C03.0'~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         
         C031=as.numeric(C031),
         C032=as.numeric(C032),
         C033=as.numeric(C033),
         C034=as.numeric(C034),
         
         C0400=factor(case_when(trimws(C0400)=='C04.00'~1,TRUE~0),
                      levels = c(0,1),
                      labels = c('Não','Sim')),
         
         C0401=as.numeric(C0401),
         C0402=as.numeric(C0402),
         C0403=as.numeric(C0403),
         C0404=as.numeric(C0404),
         C0405=as.numeric(C0405),
         C0406=as.numeric(C0406),
         C0407=as.numeric(C0407),
         C0408=as.numeric(C0408),
         C0409=as.numeric(C0409),
         C0410=as.numeric(C0410),
         C0411=as.numeric(C0411),
         C0412=as.numeric(C0412),
         C0413=as.numeric(C0413),
         C0414=as.numeric(C0414),
         C0415=as.numeric(C0415),
         C0416=as.numeric(C0416),
         C0417=as.numeric(C0417),
         C0418=as.numeric(C0418),
         C0419=as.numeric(C0419),
         C0420=as.numeric(C0420),
         C0421=as.numeric(C0421),
         C0422=as.numeric(C0422),
         C0477=as.numeric(case_when(trimws(C0477)=='C04.77'~77)),
         
         C050=factor(case_when(trimws(C050)=='C05.0'~1,TRUE~0),
                     levels = c(0,1),
                     labels = c('Não','Sim')),
         
         #C051=as.numeric(C051),
         C052=as.numeric(C052),
         C053=as.numeric(C053),
         
         C061=factor(str_replace(trimws(C061),'C06.','')),
         
         C062=factor(str_replace(trimws(C062),'C06.','')),
         
         C063=factor(str_replace(trimws(C063),'C06.','')),
         
         C064=factor(str_replace(trimws(C064),'C06.','')),
         
         C065=factor(str_replace(trimws(C065),'C06.','')),
         
         C066=factor(str_replace(trimws(C066),'C06.','')),
         
         C07=factor(case_when(trimws(C07)=='C07.1'~1,
                              trimws(C07)=='C07.2'~2,
                              trimws(C07)=='C07.3'~3,
                              trimws(C07)=='C07.8'~8),
                    levels = c(1:3,8),
                    labels = c( 'Existem vários na região',
                                'Não tem banco',
                                'Não há bancos suficientes',
                                'Não sabe/não quis responder')),
         
         C08=factor(case_when(trimws(C08)=='C08.1'~1,
                              trimws(C08)=='C08.2'~2,
                              trimws(C08)=='C08.3'~3,
                              trimws(C08)=='C08.4'~4,
                              trimws(C08)=='C08.8'~8),
                    levels = c(1:4,8),
                    labels = c( 'Utilizo vários bancos',
                                'Utilizo apenas um banco',
                                'Uso os canais eletrônicos',
                                'Não uso porque considero os serviços/produtos/taxas insatisfatórios', 
                                'Não sabe/não quis responder')),
         
         C09=factor(case_when(trimws(C09)=='C09.01'~01,
                              trimws(C09)=='C09.02'~02,
                              trimws(C09)=='C09.03'~03,
                              trimws(C09)=='C09.04'~04,
                              trimws(C09)=='C09.05'~05,
                              trimws(C09)=='C09.06'~06,
                              trimws(C09)=='C09.07'~07,
                              trimws(C09)=='C09.08'~08,
                              trimws(C09)=='C09.09'~09,
                              trimws(C09)=='C09.88'~88),
                    levels = c(1:9,88),
                    labels = c( 'Cartão de Crédito',
                                'Financiamento/Empréstimo',
                                'Investimento',
                                'Recebimento de contas',
                                'Seguro',
                                'Previdência',
                                'Canais de atendimento',
                                'Recebimento de salário',
                                'Outros',
                                'Não sabe/não quis responder')),
         
         C101=factor(case_when(trimws(C101)=='C10.1'~1,
                               trimws(C101)=='C10.2'~2,
                               trimws(C101)=='C10.3'~3,
                               trimws(C101)=='C10.4'~4,
                               trimws(C101)=='C10.5'~5,
                               trimws(C101)=='C10.6'~6,
                               trimws(C101)=='C10.7'~7,
                               trimws(C101)=='C10.8'~8,
                               trimws(C101)=='C10.9'~9),
                     levels = c(1:9),
                     labels = c( 'Bradesco',
                                 'Banco Regional de Brasília - BRB',
                                 'Banco do Brasil - BB',
                                 'Caixa Econômica Federal - CEF',
                                 'Itaú',
                                 'Safra',
                                 'Santander',
                                 'Outros',
                                 'Não sabe/não quis responder')),
         
         C102=factor(case_when(trimws(C102)=='C10.1'~1,
                               trimws(C102)=='C10.2'~2,
                               trimws(C102)=='C10.3'~3,
                               trimws(C102)=='C10.4'~4,
                               trimws(C102)=='C10.5'~5,
                               trimws(C102)=='C10.6'~6,
                               trimws(C102)=='C10.7'~7,
                               trimws(C102)=='C10.8'~8,
                               trimws(C102)=='C10.9'~9),
                     levels = c(1:9),
                     labels = c( 'Bradesco',
                                 'Banco Regional de Brasília - BRB',
                                 'Banco do Brasil - BB',
                                 'Caixa Econômica Federal - CEF',
                                 'Itaú',
                                 'Safra',
                                 'Santander',
                                 'Outros',
                                 'Não sabe/não quis responder')),
         
         C103=factor(case_when(trimws(C103)=='C10.1'~1,
                               trimws(C103)=='C10.2'~2,
                               trimws(C103)=='C10.3'~3,
                               trimws(C103)=='C10.4'~4,
                               trimws(C103)=='C10.5'~5,
                               trimws(C103)=='C10.6'~6,
                               trimws(C103)=='C10.7'~7,
                               trimws(C103)=='C10.8'~8,
                               trimws(C103)=='C10.9'~9),
                     levels = c(1:9),
                     labels = c( 'Bradesco',
                                 'Banco Regional de Brasília - BRB',
                                 'Banco do Brasil - BB',
                                 'Caixa Econômica Federal - CEF',
                                 'Itaú',
                                 'Safra',
                                 'Santander',
                                 'Outros',
                                 'Não sabe/não quis responder')),
         
         C104=factor(case_when(trimws(C104)=='C10.1'~1,
                               trimws(C104)=='C10.2'~2,
                               trimws(C104)=='C10.3'~3,
                               trimws(C104)=='C10.4'~4,
                               trimws(C104)=='C10.5'~5,
                               trimws(C104)=='C10.6'~6,
                               trimws(C104)=='C10.7'~7,
                               trimws(C104)=='C10.8'~8,
                               trimws(C104)=='C10.9'~9),
                     levels = c(1:9),
                     labels = c( 'Bradesco',
                                 'Banco Regional de Brasília - BRB',
                                 'Banco do Brasil - BB',
                                 'Caixa Econômica Federal - CEF',
                                 'Itaú',
                                 'Safra',
                                 'Santander',
                                 'Outros',
                                 'Não sabe/não quis responder'))
  ) 

#Tratamento dos "Saltos"
domicilio <- domicilio %>% 
  mutate(B04=as.numeric(case_when(as.numeric(B03) %in% c(1,3,4,5,6,7,8,9,10,11,12,13,14,15)~99999,
                                  TRUE~B04)),
         
         B05=as.numeric(case_when(as.numeric(B03) %in% c(1,2,3,4,5,10,11,12,13,14,15)~99999,
                                  B04>=0~99999,
                                  TRUE~B05)),
         
         C09=factor(case_when(as.numeric(C08)==4~99,
                              TRUE~as.numeric(C09)),
                    levels = c(1:9,88,99),
                    labels = c( 'Cartão de Crédito',
                                'Financiamento/Empréstimo',
                                'Investimento',
                                'Recebimento de contas',
                                'Seguro',
                                'Previdência',
                                'Canais de atendimento',
                                'Recebimento de salário',
                                'Outros',
                                'Não sabe/não quis responder',
                                'Não se aplica'))
  ) 

m <- sqlQuery(db,"select * from pmad2018.moradores_1023")

moradores <- m %>%  
  mutate(A01nficha=as.numeric(A01nficha),
         situacao=as.numeric(situacao),
         A01npessoas=as.numeric(A01npessoas),
         D02=factor(case_when(trimws(D02)=='D02.01'~1,
                              trimws(D02)=='D02.02'~2,
                              trimws(D02)=='D02.03'~3,
                              trimws(D02)=='D02.04'~4,
                              trimws(D02)=='D02.05'~5,
                              trimws(D02)=='D02.06'~6,
                              trimws(D02)=='D02.07'~7,
                              trimws(D02)=='D02.08'~8,
                              trimws(D02)=='D02.09'~9,
                              trimws(D02)=='D02.10'~10),
                    levels = c(1:10),
                    labels = c('Pessoa responsável pelo domicílio',
                               'Cônjuge ou companheiro(a) de sexo diferente',
                               'Cônjuge ou companheiro(a) do mesmo sexo',
                               'Filho(a)',
                               'Enteado',
                               'Outro parente',
                               'Agregado(a) (Não é parente da pessoa de referência da família ou do cônjuge e não paga hospedagem nem alimentação)',
                               'Pensionista (Não é parente da pessoa de referência da família ou do cônjuge e paga hospedagem) e/ou Alimentação',
                               'Empregado(a) doméstico(a)',
                               'Outros')),
         D03=factor(case_when(trimws(D03)=='D03.1'~1,
                              trimws(D03)=='D03.2'~2),
                    levels = c(1,2),
                    labels = c('Masculino','Feminino')),
         D04=factor(case_when(trimws(D04)=='D04.1'~1,
                              trimws(D04)=='D04.2'~2,
                              trimws(D04)=='D04.3'~3,
                              trimws(D04)=='D04.4'~4,
                              trimws(D04)=='D04.5'~5,
                              trimws(D04)=='D04.8'~8),
                    levels = c(1:5,8),
                    labels = c('Branca',
                               'Preta',
                               'Amarela',
                               'Parda',
                               'Indígena',
                               'Não sabe/Não quis responder')),
         D05=case_when(trimws(D051)=='D05.000'~0,TRUE~as.numeric(D05)),
         D06=factor(case_when(trimws(D06)=='D06.0'~0,
                              trimws(D06)=='D06.1'~1),
                    levels = c(0,1),
                    labels = c('Não',
                               'Sim')),
         D07=factor(case_when(trimws(D07)=='D07.1'~1,
                              trimws(D07)=='D07.2'~2,
                              trimws(D07)=='D07.3'~3,
                              trimws(D07)=='D07.4'~4,
                              trimws(D07)=='D07.5'~5,
                              trimws(D07)=='D07.6'~6,
                              trimws(D07)=='D07.7'~7,
                              trimws(D07)=='D07.8'~8),
                    levels = c(1:8),
                    labels = c('Solteiro',
                               'Casado Civil',
                               'Casado Religioso',
                               'Civil e Religioso',
                               'Divorciado',
                               'Separado',
                               'União estável',
                               'Viúvo')),
         D08=factor(case_when(trimws(D08)=='D08.0'~0,
                              trimws(D08)=='D08.1'~1,
                              trimws(D08)=='D08.2'~2,
                              trimws(D08)=='D08.3'~3,
                              trimws(D08)=='D08.4'~4,
                              trimws(D08)=='D08.5'~5,
                              trimws(D08)=='D08.6'~6,
                              trimws(D08)=='D08.7'~7,
                              trimws(D08)=='D08.8'~8),
                    levels = c(0:8),
                    labels = c('Não tem religão',
                               'Catórlica',
                               'Evangélica tradicional',
                               'Evangélica pentecostal',
                               'Espírita',
                               'Oriental',
                               'Origem afro',
                               'Outras',
                               'Não sabe/Não quis responder')),
         D09=factor(case_when(trimws(D09)=='D09.0'~0,
                              trimws(D09)=='D09.1'~1,
                              trimws(D09)=='D09.2'~2,
                              trimws(D09)=='D09.8'~8),
                    levels = c(0:2,8),
                    labels = c('Não frequenta',
                               'Praticante regular',
                               'Praticante eventual',
                               'Não sabe/não quis responder')),
         D10=factor(case_when(trimws(D10)=='D10.01'~01,
                              trimws(D10)=='D10.02'~02,
                              trimws(D10)=='D10.03'~03,
                              trimws(D10)=='D10.04'~04,
                              trimws(D10)=='D10.05'~05,
                              trimws(D10)=='D10.06'~06,
                              trimws(D10)=='D10.07'~07,
                              trimws(D10)=='D10.08'~08,
                              trimws(D10)=='D10.09'~09,
                              trimws(D10)=='D10.10'~10,
                              trimws(D10)=='D10.11'~11,
                              trimws(D10)=='D10.12'~12,
                              trimws(D10)=='D10.13'~13,
                              trimws(D10)=='D10.14'~14,
                              trimws(D10)=='D10.15'~15,
                              trimws(D10)=='D10.16'~16,
                              trimws(D10)=='D10.17'~17,
                              trimws(D10)=='D10.18'~18,
                              trimws(D10)=='D10.19'~19,
                              trimws(D10)=='D10.20'~20,
                              trimws(D10)=='D10.21'~21,
                              trimws(D10)=='D10.22'~22,
                              trimws(D10)=='D10.23'~23,
                              trimws(D10)=='D10.24'~24,
                              trimws(D10)=='D10.25'~25,
                              trimws(D10)=='D10.26'~26,
                              trimws(D10)=='D10.27'~27,
                              trimws(D10)=='D10.28'~28,
                              trimws(D10)=='D10.88'~88),
                    levels = c(1:28,88),
                    labels = c('Distrito Federal',
                               'Acre',
                               'Alagoas',
                               'Amapá',
                               'Amazonas',
                               'Bahia',
                               'Ceará',
                               'Espírito Santo',
                               'Goiás',
                               'Maranhão',
                               'Mato Grosso',
                               'Mato Grosso do Sul',
                               'Minas Gerais',
                               'Pará',
                               'Paraíba',
                               'Paraná',
                               'Pernambuco',
                               'Piauí',
                               'Rio de Janeiro',
                               'Rio Grande do Norte',
                               'Rio Grande do Sul',
                               'Rondônia',
                               'Roraima',
                               'Santa Catarina',
                               'São Paulo',
                               'Sergipe',
                               'Tocantins',
                               'Exterior',
                               'Não sabe/Não quis informar')),
         D11=factor(case_when(trimws(D11)=='D11.1'~1,
                              trimws(D11)=='D11.2'~2,
                              trimws(D11)=='D11.3'~3,
                              trimws(D11)=='D11.4'~4,
                              trimws(D11)=='D11.8'~8,
                              trimws(D11)=='D11.9'~9),
                    levels = c(1:4,8,9),
                    labels = c('No DF',
                               'No município',
                               'Outro município da PMB',
                               'Em outro local',
                               'Não sabe/Não quis responder',
                               'Nascidos fora do DF')),
         D12=case_when(trimws(D12)=='D12.88'~88,TRUE~as.numeric(D121)),
         D13=factor(case_when(trimws(D13)=='D13.01'~01,
                              trimws(D13)=='D13.02'~02,
                              trimws(D13)=='D13.03'~03,
                              trimws(D13)=='D13.04'~04,
                              trimws(D13)=='D13.05'~05,
                              trimws(D13)=='D13.06'~06,
                              trimws(D13)=='D13.07'~07,
                              trimws(D13)=='D13.08'~08,
                              trimws(D13)=='D13.09'~09,
                              trimws(D13)=='D13.10'~10,
                              trimws(D13)=='D13.11'~11,
                              trimws(D13)=='D13.12'~12,
                              trimws(D13)=='D13.13'~13,
                              trimws(D13)=='D13.14'~14,
                              trimws(D13)=='D13.15'~15,
                              trimws(D13)=='D13.16'~16,
                              trimws(D13)=='D13.17'~17,
                              trimws(D13)=='D13.18'~18,
                              trimws(D13)=='D13.19'~19,
                              trimws(D13)=='D13.20'~20,
                              trimws(D13)=='D13.21'~21,
                              trimws(D13)=='D13.22'~22,
                              trimws(D13)=='D13.23'~23,
                              trimws(D13)=='D13.24'~24,
                              trimws(D13)=='D13.25'~25,
                              trimws(D13)=='D13.26'~26,
                              trimws(D13)=='D13.27'~27,
                              trimws(D13)=='D13.28'~28,
                              trimws(D13)=='D13.88'~88,
                              trimws(D13)=='D13.99'~99),
                    levels = c(1:28,88,99),
                    labels = c('Distrito Federal',
                               'Acre',
                               'Alagoas',
                               'Amapá',
                               'Amazonas',
                               'Bahia',
                               'Ceará',
                               'Espírito Santo',
                               'Goiás',
                               'Maranhão',
                               'Mato Grosso',
                               'Mato Grosso do Sul',
                               'Minas Gerais',
                               'Pará',
                               'Paraíba',
                               'Paraná',
                               'Pernambuco',
                               'Piauí',
                               'Rio de Janeiro',
                               'Rio Grande do Norte',
                               'Rio Grande do Sul',
                               'Rondônia',
                               'Roraima',
                               'Santa Catarina',
                               'São Paulo',
                               'Sergipe',
                               'Tocantins',
                               'Exterior',
                               'Não sabe/Não quis informar',
                               'Nascidos no município')),
         D14=factor(case_when(trimws(D14)=='D14.01'~01,
                              trimws(D14)=='D14.02'~02,
                              trimws(D14)=='D14.03'~03,
                              trimws(D14)=='D14.04'~04,
                              trimws(D14)=='D14.05'~05,
                              trimws(D14)=='D14.06'~06,
                              trimws(D14)=='D14.07'~07,
                              trimws(D14)=='D14.08'~08,
                              trimws(D14)=='D14.09'~09,
                              trimws(D14)=='D14.88'~88,
                              trimws(D14)=='D14.99'~99),
                    levels = c(1:9,88,99),
                    labels = c('Acompanhar Parentes/Reunião Familiar',
                               'Estudo e ou escola',
                               'Aquisição moradia',
                               'Programa de Governo para Moradia',
                               'Transferência de trabalho',
                               'Procura de Trabalho',
                               'Melhor acesso aos serviços de saúde',
                               'Mudança de estado civil',
                               'Outros Motivos',
                               'Não Sabe',
                               'Nascidos no município')),
         D15=case_when(trimws(D15)=='D15.88'~888,TRUE~as.numeric(D151)),
         D16=factor(case_when(trimws(D16)=='D16.0'~0,
                              trimws(D16)=='D16.1'~1,
                              trimws(D16)=='D16.2'~2,
                              trimws(D16)=='D16.3'~3,
                              trimws(D16)=='D16.4'~4,
                              trimws(D16)=='D16.5'~5,
                              trimws(D16)=='D16.8'~8),
                    levels = c(0:5,8),
                    labels = c('Não acessa',
                               'Computador de casa',
                               'Computador do trabalho',
                               'Celular',
                               'Tablet',
                               'Lan House',
                               'Não sabe/não quis responder')),
         D17=factor(case_when(trimws(D17)=='D17.0'~0,
                              trimws(D17)=='D17.1'~1,
                              trimws(D17)=='D17.2'~2,
                              trimws(D17)=='D17.8'~8),
                    levels = c(0:2,8),
                    labels = c('Não possui',
                               'Empresarial',
                               'Particular',
                               'Não sabe/não quis responder')),
         D18=factor(case_when(trimws(D18)=='D18.00'~00,
                              trimws(D18)=='D18.01'~01,
                              trimws(D18)=='D18.02'~02,
                              trimws(D18)=='D18.03'~03,
                              trimws(D18)=='D18.04'~04,
                              trimws(D18)=='D18.05'~05,
                              trimws(D18)=='D18.06'~06,
                              trimws(D18)=='D18.07'~07,
                              trimws(D18)=='D18.08'~08,
                              trimws(D18)=='D18.09'~09,
                              trimws(D18)=='D18.10'~10,
                              trimws(D18)=='D18.11'~11,
                              trimws(D18)=='D18.12'~12,
                              trimws(D18)=='D18.13'~13,
                              trimws(D18)=='D18.14'~14,
                              trimws(D18)=='D18.15'~15,
                              trimws(D18)=='D18.16'~16,
                              trimws(D18)=='D18.17'~17,
                              trimws(D18)=='D18.18'~18,
                              trimws(D18)=='D18.19'~19,
                              trimws(D18)=='D18.20'~20,
                              trimws(D18)=='D18.21'~21,
                              trimws(D18)=='D18.22'~22,
                              trimws(D18)=='D18.23'~23,
                              trimws(D18)=='D18.24'~24,
                              trimws(D18)=='D18.25'~25,
                              trimws(D18)=='D18.26'~26,
                              trimws(D18)=='D18.27'~27,
                              trimws(D18)=='D18.28'~28,
                              trimws(D18)=='D18.29'~29,
                              trimws(D18)=='D18.30'~30,
                              trimws(D18)=='D18.31'~31,
                              trimws(D18)=='D18.32'~32,
                              trimws(D18)=='D18.41'~41,
                              trimws(D18)=='D18.42'~42,
                              trimws(D18)=='D18.43'~43,
                              trimws(D18)=='D18.44'~44,
                              trimws(D18)=='D18.45'~45,
                              trimws(D18)=='D18.46'~46,
                              trimws(D18)=='D18.47'~47,
                              trimws(D18)=='D18.48'~48,
                              trimws(D18)=='D18.49'~49,
                              trimws(D18)=='D18.50'~50,
                              trimws(D18)=='D18.51'~51,
                              trimws(D18)=='D18.52'~52,
                              trimws(D18)=='D18.53'~53,
                              trimws(D18)=='D18.54'~54,
                              trimws(D18)=='D18.55'~55,
                              trimws(D18)=='D18.56'~56,
                              trimws(D18)=='D18.88'~88),
                    levels = c(0:32,41:56,88),
                    labels = c('Não utiliza',
                               'Plano Piloto',
                               'Gama',
                               'Taguatinga',
                               'Brazlândia',
                               'Sobradinho',
                               'Planaltina',
                               'Paranoá',
                               'Núcleo Bandeirante',
                               'Ceilândia',
                               'Guará',
                               'Cruzeiro',
                               'Samambaia',
                               'Santa Maria',
                               'São Sebastião',
                               'Recanto das Emas',
                               'Lago Sul',
                               'Riacho Fundo',
                               'Lago Norte',
                               'Candangolândia',
                               'Águas Claras',
                               'Riacho Fundo II',
                               'Sudoeste/Octogonal',
                               'Varjão',
                               'Park Way',
                               'SCIA-Estrutural',
                               'Sobradinho II',
                               'Jardim Botânico',
                               'Itapoã',
                               'SIA',
                               'Vicente Pires',
                               'Fercal',
                               'Vários locais do DF',
                               'Aguas Lindas de Goiás',
                               'Alexânia',
                               'Cidade Ocidental (Sede e ABC)',
                               'Cristalina (Sede, Campos Lindos/ Marajó)',
                               'Cocalzinho de Goiás (Sede, Girassol/Edilândia)',
                               'Formosa',
                               'Luziânia (Sede e Distritos)',
                               'Novo Gama',
                               'Padre Bernardo (Sede, Monte Alto)',
                               'Planaltina',
                               'Santo Antônio do Descoberto',
                               'Valparaíso de Goiás',
                               'Outros municípios da RIDE',
                               'Anápolis',
                               'Goiânia',
                               'Outros locais',
                               'Não sabe/não quis responder')),
         D19=factor(case_when(trimws(D19)=='D19.00'~00,
                              trimws(D19)=='D19.01'~01,
                              trimws(D19)=='D19.02'~02,
                              trimws(D19)=='D19.03'~03,
                              trimws(D19)=='D19.04'~04,
                              trimws(D19)=='D19.05'~05,
                              trimws(D19)=='D19.06'~06,
                              trimws(D19)=='D19.07'~07,
                              trimws(D19)=='D19.08'~08,
                              trimws(D19)=='D19.09'~09,
                              trimws(D19)=='D19.10'~10,
                              trimws(D19)=='D19.11'~11,
                              trimws(D19)=='D19.12'~12,
                              trimws(D19)=='D19.13'~13,
                              trimws(D19)=='D19.14'~14,
                              trimws(D19)=='D19.15'~15,
                              trimws(D19)=='D19.16'~16,
                              trimws(D19)=='D19.17'~17,
                              trimws(D19)=='D19.18'~18,
                              trimws(D19)=='D19.19'~19,
                              trimws(D19)=='D19.20'~20,
                              trimws(D19)=='D19.21'~21,
                              trimws(D19)=='D19.22'~22,
                              trimws(D19)=='D19.23'~23,
                              trimws(D19)=='D19.24'~24,
                              trimws(D19)=='D19.25'~25,
                              trimws(D19)=='D19.26'~26,
                              trimws(D19)=='D19.27'~27,
                              trimws(D19)=='D19.28'~28,
                              trimws(D19)=='D19.29'~29,
                              trimws(D19)=='D19.30'~30,
                              trimws(D19)=='D19.31'~31,
                              trimws(D19)=='D19.32'~32,
                              trimws(D19)=='D19.41'~41,
                              trimws(D19)=='D19.42'~42,
                              trimws(D19)=='D19.43'~43,
                              trimws(D19)=='D19.44'~44,
                              trimws(D19)=='D19.45'~45,
                              trimws(D19)=='D19.46'~46,
                              trimws(D19)=='D19.47'~47,
                              trimws(D19)=='D19.48'~48,
                              trimws(D19)=='D19.49'~49,
                              trimws(D19)=='D19.50'~50,
                              trimws(D19)=='D19.51'~51,
                              trimws(D19)=='D19.52'~52,
                              trimws(D19)=='D19.53'~53,
                              trimws(D19)=='D19.54'~54,
                              trimws(D19)=='D19.55'~55,
                              trimws(D19)=='D19.56'~56,
                              trimws(D19)=='D19.88'~88),
                    levels = c(0:32,41:56,88),
                    labels = c('Não utiliza',
                               'Plano Piloto',
                               'Gama',
                               'Taguatinga',
                               'Brazlândia',
                               'Sobradinho',
                               'Planaltina',
                               'Paranoá',
                               'Núcleo Bandeirante',
                               'Ceilândia',
                               'Guará',
                               'Cruzeiro',
                               'Samambaia',
                               'Santa Maria',
                               'São Sebastião',
                               'Recanto das Emas',
                               'Lago Sul',
                               'Riacho Fundo',
                               'Lago Norte',
                               'Candangolândia',
                               'Águas Claras',
                               'Riacho Fundo II',
                               'Sudoeste/Octogonal',
                               'Varjão',
                               'Park Way',
                               'SCIA-Estrutural',
                               'Sobradinho II',
                               'Jardim Botânico',
                               'Itapoã',
                               'SIA',
                               'Vicente Pires',
                               'Fercal',
                               'Vários locais do DF',
                               'Aguas Lindas de Goiás',
                               'Alexânia',
                               'Cidade Ocidental (Sede e ABC)',
                               'Cristalina (Sede, Campos Lindos/ Marajó)',
                               'Cocalzinho de Goiás (Sede, Girassol/Edilândia)',
                               'Formosa',
                               'Luziânia (Sede e Distritos)',
                               'Novo Gama',
                               'Padre Bernardo (Sede, Monte Alto)',
                               'Planaltina',
                               'Santo Antônio do Descoberto',
                               'Valparaíso de Goiás',
                               'Outros municípios da RIDE',
                               'Anápolis',
                               'Goiânia',
                               'Outros locais',
                               'Não sabe/não quis responder')),
         D20=factor(case_when(trimws(D20)=='D20.0'~00,
                              trimws(D20)=='D20.1'~01,
                              trimws(D20)=='D20.2'~02,
                              trimws(D20)=='D20.3'~03,
                              trimws(D20)=='D20.4'~04,
                              trimws(D20)=='D20.5'~05,
                              trimws(D20)=='D20.6'~06,
                              trimws(D20)=='D20.7'~07,
                              trimws(D20)=='D20.8'~08,
                              trimws(D20)=='D20.9'~09,
                              trimws(D20)=='D20.10'~10,
                              trimws(D20)=='D20.11'~11,
                              trimws(D20)=='D20.12'~12,
                              trimws(D20)=='D20.13'~13,
                              trimws(D20)=='D20.14'~14,
                              trimws(D20)=='D20.88'~88),
                    levels = c(0:14,88),
                    labels = c('Não sofreu',
                               'Roubo de carros',
                               'Furto de carros',
                               'Furto de dentro do carro',
                               'Dano/vandalismo de carros',
                               'Roubo de motocicletas/lambretas',
                               'Furto de motocicletas/lambretas',
                               'Roubo de bicicletas',
                               'Furto de bicicleta',
                               'Arrombamento',
                               'Tentativa de arrombamento',
                               'Roubo de outros bens',
                               'Furto pessoais',
                               'Ofensa sexual',
                               'Agressão física/ameaças',
                               'Não sabe/não lembra')),
         D21=factor(case_when(trimws(D21)=='D21.1'~01,
                              trimws(D21)=='D21.2'~02,
                              trimws(D21)=='D21.3'~03,
                              trimws(D21)=='D21.4'~04,
                              trimws(D21)=='D21.5'~05,
                              trimws(D21)=='D21.6'~06,
                              trimws(D21)=='D21.7'~07,
                              trimws(D21)=='D21.8'~08),
                    levels = c(1:8),
                    labels = c('Na sua casa',
                               'Na casa de algum parente ou amigo',
                               'Andando na rua',
                               'No local de trabalho',
                               'Meios de transporte (ônibus, metrô, trem, táxi, lotação, carro, etc.)',
                               'Locais públicos internos (banco, escola, shopping, restaurantes, bar, loja, etc)',
                               'Locais públicos externos (praça, parque, jardim, etc)',
                               'Não sabe/não lembra')),
         D22=factor(case_when(trimws(D22)=='D22.1'~01,
                              trimws(D22)=='D22.2'~02,
                              trimws(D22)=='D22.3'~03,
                              trimws(D22)=='D22.4'~04,
                              trimws(D22)=='D22.5'~05,
                              trimws(D22)=='D22.8'~08),
                    levels = c(1:5,8),
                    labels = c('Não denunciou',
                               'Sim na Polícia Militar',
                               'Sim na Polícia Civil',
                               'Sim na Polícia Rodoviária Federal',
                               'Sim outra',
                               'Não sabe/não lembra')),
         E01=factor(case_when(trimws(E01)=='E01.0'~00,
                              trimws(E01)=='E01.1'~01,
                              trimws(E01)=='E01.2'~02,
                              trimws(E01)=='E01.3'~03,
                              trimws(E01)=='E01.4'~04),
                    levels = c(0:4),
                    labels = c('Não',
                               'Escola pública',
                               'Escola particular',
                               'A distância pública',
                               'A distância particular')),
         E02=factor(case_when(trimws(E02)=='E02.01'~01,
                              trimws(E02)=='E02.02'~02,
                              trimws(E02)=='E02.03'~03,
                              trimws(E02)=='E02.04'~04,
                              trimws(E02)=='E02.05'~05,
                              trimws(E02)=='E02.06'~06,
                              trimws(E02)=='E02.07'~07,
                              trimws(E02)=='E02.08'~08,
                              trimws(E02)=='E02.09'~09,
                              trimws(E02)=='E02.10'~10,
                              trimws(E02)=='E02.11'~11,
                              trimws(E02)=='E02.12'~12,
                              trimws(E02)=='E02.13'~13,
                              trimws(E02)=='E02.14'~14,
                              trimws(E02)=='E02.15'~15,
                              trimws(E02)=='E02.16'~16,
                              trimws(E02)=='E02.17'~17,
                              trimws(E02)=='E02.18'~18,
                              trimws(E02)=='E02.19'~19,
                              trimws(E02)=='E02.20'~20,
                              trimws(E02)=='E02.21'~21,
                              trimws(E02)=='E02.22'~22,
                              trimws(E02)=='E02.23'~23,
                              trimws(E02)=='E02.24'~24,
                              trimws(E02)=='E02.25'~25,
                              trimws(E02)=='E02.26'~26,
                              trimws(E02)=='E02.27'~27,
                              trimws(E02)=='E02.28'~28,
                              trimws(E02)=='E02.29'~29,
                              trimws(E02)=='E02.30'~30,
                              trimws(E02)=='E02.31'~31,
                              trimws(E02)=='E02.32'~32,
                              trimws(E02)=='E02.41'~41,
                              trimws(E02)=='E02.42'~42,
                              trimws(E02)=='E02.43'~43,
                              trimws(E02)=='E02.44'~44,
                              trimws(E02)=='E02.45'~45,
                              trimws(E02)=='E02.46'~46,
                              trimws(E02)=='E02.47'~47,
                              trimws(E02)=='E02.48'~48,
                              trimws(E02)=='E02.49'~49,
                              trimws(E02)=='E02.50'~50,
                              trimws(E02)=='E02.51'~51,
                              trimws(E02)=='E02.52'~52,
                              trimws(E02)=='E02.53'~53,
                              trimws(E02)=='E02.54'~54,
                              trimws(E02)=='E02.55'~55,
                              trimws(E02)=='E02.56'~56,
                              trimws(E02)=='E02.88'~88),
                    levels = c(01:32,41:56,88),
                    labels = c('Plano Piloto',
                               'Gama',
                               'Taguatinga',
                               'Brazlândia',
                               'Sobradinho',
                               'Planaltina',
                               'Paranoá',
                               'Núcleo Bandeirante',
                               'Ceilândia',
                               'Guará',
                               'Cruzeiro',
                               'Samambaia',
                               'Santa Maria',
                               'São Sebastião',
                               'Recanto das Emas',
                               'Lago Sul',
                               'Riacho Fundo',
                               'Lago Norte',
                               'Candangolândia',
                               'Águas Claras',
                               'Riacho Fundo II',
                               'Sudoeste/Octogonal',
                               'Varjão',
                               'Park Way',
                               'SCIA-Estrutural',
                               'Sobradinho II',
                               'Jardim Botânico',
                               'Itapoã',
                               'SIA',
                               'Vicente Pires',
                               'Fercal',
                               'Vários locais do DF',
                               'Aguas Lindas de Goiás',
                               'Alexânia',
                               'Cidade Ocidental (Sede e ABC)',
                               'Cristalina (Sede, Campos Lindos/ Marajó)',
                               'Cocalzinho de Goiás (Sede, Girassol/Edilândia)',
                               'Formosa',
                               'Luziânia (Sede e Distritos)',
                               'Novo Gama',
                               'Padre Bernardo (Sede, Monte Alto)',
                               'Planaltina',
                               'Santo Antônio do Descoberto',
                               'Valparaíso de Goiás',
                               'Outros municípios da RIDE',
                               'Anápolis',
                               'Goiânia',
                               'Outros locais',
                               'Não sabe/não quis responder'))
  ) 

table(domicilio$B04,useNA = "ifany")

table(domicilio$C09,useNA = "ifany")

View(domicilio %>% dplyr::filter(is.na(B04)==TRUE))

,
E03=factor(case_when(trimws(E03)=='E03.01'~01,
                     trimws(E02)=='E02.02'~02,
                     trimws(E02)=='E02.03'~03,
                     trimws(E02)=='E02.04'~04,
                     trimws(E02)=='E02.05'~05,
                     trimws(E02)=='E02.06'~06,
                     trimws(E02)=='E02.07'~07,
                     trimws(E02)=='E02.08'~08,
                     trimws(E02)=='E02.09'~09,
                     trimws(E02)=='E02.10'~10,
                     trimws(E02)=='E02.11'~11,
                     trimws(E02)=='E02.12'~12,
                     trimws(E02)=='E02.13'~13,
                     trimws(E02)=='E02.14'~14,
                     trimws(E02)=='E02.15'~15,
                     trimws(E02)=='E02.16'~16,
                     trimws(E02)=='E02.17'~17,
                     trimws(E02)=='E02.18'~18,
                     trimws(E02)=='E02.19'~19,
                     trimws(E02)=='E02.20'~20,
                     trimws(E02)=='E02.21'~21,
                     trimws(E02)=='E02.22'~22,
                     trimws(E02)=='E02.23'~23,
                     trimws(E02)=='E02.24'~24,
                     trimws(E02)=='E02.25'~25,
                     trimws(E02)=='E02.26'~26,
                     trimws(E02)=='E02.27'~27,
                     trimws(E02)=='E02.28'~28,
                     trimws(E02)=='E02.29'~29,
                     trimws(E02)=='E02.30'~30,
                     trimws(E02)=='E02.31'~31,
                     trimws(E02)=='E02.32'~32,
                     trimws(E02)=='E02.41'~41,
                     trimws(E02)=='E02.42'~42,
                     trimws(E02)=='E02.43'~43,
                     trimws(E02)=='E02.44'~44,
                     trimws(E02)=='E02.45'~45,
                     trimws(E02)=='E02.46'~46,
                     trimws(E02)=='E02.47'~47,
                     trimws(E02)=='E02.48'~48,
                     trimws(E02)=='E02.49'~49,
                     trimws(E02)=='E02.50'~50,
                     trimws(E02)=='E02.51'~51,
                     trimws(E02)=='E02.52'~52,
                     trimws(E02)=='E02.53'~53,
                     trimws(E02)=='E02.54'~54,
                     trimws(E02)=='E02.55'~55,
                     trimws(E02)=='E02.56'~56,
                     trimws(E02)=='E02.88'~88),
           labels = c('Plano Piloto',
                      'Taguatinga',
                      'Brazlândia',
                      'Ceilândia',
                      'Guará',
                      'Recanto das Emas',
                      'Águas Claras',
                      'Aguas Lindas de Goiás',
                      'Outros locais'))