library(RODBC)
library(dplyr)
library(srvyr)
library(stringr)

rm(list = ls())
db <- odbcConnect("DB_CODEPLAN", uid=35866, pwd='Meliodas083')
sqlTables(db) %>% 
  filter(TABLE_SCHEM=="pmad2018") %>%
  select(TABLE_NAME)

domicilio <- sqlQuery(db,"select * from pmad2018.domicilios_1023")

colnames(domicilio)

str_detect(colnames(domicilio),'C01')

table(domicilio$B02,useNA = "ifany")

#Atribuindo mascaras para as questões
domicilio <- domicilio %>% 
  mutate(tipo=factor(case_when(trimws(tipo)=='Tipo.1'~10,
                               trimws(tipo)=='Tipo.2'~20,
                               trimws(tipo)=='Tipo.3'~30,
                               trimws(tipo)=='Tipo.4'~40,
                               trimws(tipo)=='Tipo.5'~50,
                               trimws(tipo)=='Tipo.6'~60,
                               trimws(tipo)=='Tipo.7A'~71,
                               trimws(tipo)=='Tipo.7B'~72,
                               trimws(tipo)=='Tipo.7C'~73,
                               trimws(tipo)=='Tipo.7D'~74,
                               trimws(tipo)=='Tipo.8'~80),
                     labels=c('Sim (Continuar a pesquisa)')),
                              # 'Não (Unidade fechada)',
                              # 'Não (Recusa do morador)',
                              # 'Não (Unidade vaga)',
                              # 'Não (Unidade vaga devido a uso ocasional)',
                              # 'Não (Unidade vaga devido a construção ou reforma)',
                              # 'Não (Unidade não residencial)',
                              # '72 - Não (Unidade não encontrada)',
                              # '73 - Não (Unidade de uso coletivo)',
                              # '74 - Não (Terreno vazio)',
                              # '80 - Não (Outro motivo)')),
         B01=factor(case_when(trimws(B01)=='B01.1'~1,
                              trimws(B01)=='B01.2'~2,
                              trimws(B01)=='B01.3'~3),
                    levels = c(1:3),
                    labels=c('Permanente',
                             'Improvisado',
                             'Permanente em construção')),
         B02=factor(case_when(trimws(B02)=='B02.1'~1,
                              trimws(B02)=='B02.2'~2,
                              trimws(B02)=='B02.3'~3,
                              trimws(B02)=='B02.4'~4,
                              trimws(B02)=='B02.5'~5,
                              trimws(B02)=='B02.6'~6,
                              trimws(B02)=='B02.7'~7,
                              trimws(B02)=='B02.8'~8),
                    labels=c('B02.1 - Casa',
                             'B02.2 - Barraco',
                             'B02.3 - Cômodo',
                             'B02.4 - Quitinete/Estúdio',
                             # 'B02.5 - Flat',
                             'B02.6 - Apartamento',
                             'B02.7 - Uso misto')),
                             # 'B02.8 - Outros')),
         B03=factor(case_when(trimws(B03)=='B03.1'~1,
                              trimws(B03)=='B03.2'~2,
                              trimws(B03)=='B03.3'~3,
                              trimws(B03)=='B03.4'~4,
                              trimws(B03)=='B03.5'~5,
                              trimws(B03)=='B03.6'~6,
                              trimws(B03)=='B03.7'~7,
                              trimws(B03)=='B03.8'~8,
                              trimws(B03)=='B03.9'~9,
                              trimws(B03)=='B03.10'~10,
                              trimws(B03)=='B03.11'~11,
                              trimws(B03)=='B03.12'~12,
                              trimws(B03)=='B03.13'~13,
                              trimws(B03)=='B03.14'~14,
                              trimws(B03)=='B03.15'~15),
                        labels=c('Próprio já pago (Quitado)',
                                 'Próprio ainda pagando (Em aquisição)',
                                 'Próprio em terreno não legalizado',
                                 'Próprio em assentamento',
                                 'Próprio em invasão',
                                 'Alugado',
                                 'Alugado em terreno não legalizado',
                                 'Alugado em assentamento',
                                 #'Alugado em invasão',
                                 'Cedido',
                                 'Cedido em terreno não legalizado',
                                 'Cedido em assentamento',
                                 'Cedido em invasão')),
                                 # 'Funcional',
                                 # 'Outros')),

         B04=as.numeric(case_when(trimws(B0477777)=='B04.77777'~77777,
                                  trimws(B0488888)=='B04.88888'~88888,
                                  B041>=0~B041)),
         
         B05=as.numeric(case_when(trimws(B0577777)=='B05.77777'~77777,
                                  trimws(B0588888)=='B05.88888'~88888,
                                  B051>=0~B051)),
         
         B06=factor(case_when(trimws(B06)=='B06.0'~0,
                              trimws(B06)=='B06.1'~1,
                              trimws(B06)=='B06.2'~2,
                              trimws(B06)=='B06.3'~3,
                              trimws(B06)=='B06.4'~4,
                              trimws(B06)=='B06.5'~5,
                              trimws(B06)=='B06.6'~6,
                              trimws(B06)=='B06.7'~7),
                    labels = c('Não tem imóvel próprio (Reside em um alugado, cedido ou funcional)',
                               'Escritura definitiva',
                               'Concessão de uso',
                               'Contrato de financiamento particular',
                               'Contrato de financiamento governamental',
                               'Contrato de compra e venda (Cessão de Direito)',
                               'Minha casa minha vida',
                               'Outros')),
         B07=as.numeric(B07nComodos),
         B08=as.numeric(B08nDormitorios),
         B09=as.numeric(B09nBanheiros),
         B10=factor(case_when(trimws(B10)=='B10.1'~1,
                              trimws(B10)=='B10.2'~2,
                              trimws(B10)=='B10.3'~3,
                              trimws(B10)=='B10.4'~4),
                    labels = c('Rede Geral',
                               'Poço/Cisterna',
                               'Poço Artesiano',
                               'Outros')),
         B11=factor(case_when(trimws(B11)=='B11.1'~1,
                              trimws(B11)=='B11.2'~2,
                              trimws(B11)=='B11.3'~3,
                              trimws(B11)=='B11.4'~4,
                              trimws(B11)=='B11.5'~5),
                    labels = c( 'Não tem filtro',
                                'Filtro de barro',
                                'Filtro de parede',
                                'Filtro de carvão ativado',
                                'Água Mineral')),
         B12=factor(case_when(trimws(B12)=='B12.1'~1,
                                  trimws(B12)=='B12.2'~2,
                                  trimws(B12)=='B12.3'~3,
                                  trimws(B12)=='B12.8'~8),
                    labels = c( 'Não',
                                'Sim',
                                'Não conta com Rede Geral',
                                'Não sabe/não quis responder')),
         B13=factor(case_when(trimws(B13)=='B13.1'~1,
                                  trimws(B13)=='B13.2'~2,
                                  trimws(B13)=='B13.3'~3,
                                  trimws(B13)=='B13.4'~4,
                                  trimws(B13)=='B13.8'~8),
                    labels = c( 'Não',
                                'Raramente',
                                'Frequentemente',
                                'Não conta com Rede Geral',
                                'Não sabe/não quis responder')),
         B14=factor(case_when(trimws(B14)=='B14.1'~1,
                                  trimws(B14)=='B14.2'~2,
                                  trimws(B14)=='B14.3'~3,
                                  trimws(B14)=='B14.4'~4),
                    labels = c( 'Rede Geral',
                                'Gambiarra')),
         B15=factor(case_when(trimws(B15)=='B15.1'~1,
                                  trimws(B15)=='B15.2'~2,
                                  trimws(B15)=='B15.3'~3,
                                  trimws(B15)=='B15.8'~8),
                    labels = c( 'Não',
                                'Sim')),
         B16=factor(case_when(trimws(B16)=='B16.1'~1,
                              trimws(B16)=='B16.2'~2,
                              trimws(B16)=='B16.3'~3,
                              trimws(B16)=='B16.4'~4,
                              trimws(B16)=='B16.8'~8),
                    labels = c( 'Não',
                                'Raramente',
                                'Frequentemente',
                                # 'Não conta com Rede Geral',
                                'Não sabe/não quis responder')),
         B17=factor(case_when(trimws(B17)=='B17.1'~1,
                                  trimws(B17)=='B17.2'~2,
                                  trimws(B17)=='B17.3'~3,
                                  trimws(B17)=='B17.4'~4,
                                  trimws(B17)=='B17.5'~5),
                    labels = c( 'Rede Geral',
                                'Fossa Séptica',
                                'Fossa Rudimentar',
                                'Esgoto a céu aberto')),
         B18=factor(case_when(trimws(B18)=='B18.1'~1,
                                  trimws(B18)=='B18.2'~2,
                                  trimws(B18)=='B18.3'~3,
                                  trimws(B18)=='B18.4'~4),
                    labels = c( 'Sem coleta seletiva',
                                'Com coleta seletiva',
                                'Jogado em local impróprio')),
         B190=factor(case_when(str_detect(B19,"B19.0")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B191=factor(case_when(str_detect(B19,"B19.1")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B192=factor(case_when(str_detect(B19,"B19.2")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B193=factor(case_when(str_detect(B19,"B19.3")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B194=factor(case_when(str_detect(B19,"B19.4")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B195=factor(case_when(str_detect(B19,"B19.5")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B200=factor(case_when(str_detect(B20,"B20.0")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B201=factor(case_when(str_detect(B20,"B20.1")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B202=factor(case_when(str_detect(B20,"B20.2")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B203=factor(case_when(str_detect(B20,"B20.3")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B204=factor(case_when(str_detect(B20,"B20.4")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B205=factor(case_when(str_detect(B20,"B20.5")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B206=factor(case_when(str_detect(B20,"B20.6")~1,TRUE~0),
                     labels = c('Não','Sim')),
         
         B210=factor(case_when(str_detect(B21,"B21.0")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B211=factor(case_when(str_detect(B21,"B21.1")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B212=factor(case_when(str_detect(B21,"B21.2")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B213=factor(case_when(str_detect(B21,"B21.3")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B214=factor(case_when(str_detect(B21,"B21.4")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B215=factor(case_when(str_detect(B21,"B21.5")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B216=factor(case_when(str_detect(B21,"B21.6")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B217=factor(case_when(str_detect(B21,"B21.7")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B218=factor(case_when(str_detect(B21,"B21.8")~1,TRUE~0),
                     labels = c('Não','Sim')),
         
         B220=factor(case_when(str_detect(B22,"B22.0")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B221=factor(case_when(str_detect(B22,"B22.1")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B222=factor(case_when(str_detect(B22,"B22.2")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B223=factor(case_when(str_detect(B22,"B22.3")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B224=factor(case_when(str_detect(B22,"B22.4")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B225=factor(case_when(str_detect(B22,"B22.5")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B228=factor(case_when(str_detect(B22,"B22.8")~1,TRUE~0),
                     labels = c('Não','Sim')),
         
         B230=factor(case_when(str_detect(B23,"B23.0")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B231=factor(case_when(str_detect(B23,"B23.1")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B232=factor(case_when(str_detect(B23,"B23.2")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B233=factor(case_when(str_detect(B23,"B23.3")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B234=factor(case_when(str_detect(B23,"B23.4")~1,TRUE~0),
                     labels = c('Não','Sim')),
         B238=factor(case_when(str_detect(B23,"B23.8")~1,TRUE~0),
                     labels = c('Não','Sim')),
         
         C010=factor(case_when(trimws(C010)=='C01.0'~1,TRUE~0),
                     labels = c('Não','Sim')),
         
         C011=as.numeric(C011),
         C012=as.numeric(C012),
         C013=as.numeric(C013),
         C014=as.numeric(C014),
         #C015=as.numeric(C015),
         C016=as.numeric(C016),
         C017=as.numeric(C017),
         #C018=as.numeric(C018),
         C019=as.numeric(C019),
         
         #C020=as.numeric(case_when(trimws(C020)=='C02.0'~1,TRUE~0),
         #labels = c('Não','Sim')),
         
         C021=as.numeric(C021),
         C022=as.numeric(C022),
         C023=as.numeric(C023),
         
         C030=factor(case_when(trimws(C030)=='C03.0'~1,TRUE~0),
                         labels = c('Não','Sim')),
         
         C031=as.numeric(C031),
         C032=as.numeric(C032),
         C033=as.numeric(C033),
         C034=as.numeric(C034),
         
         C0400=factor(case_when(trimws(C0400)=='C04.00'~1,TRUE~0),
                          labels = c('Não','Sim')),
         
         C0401=as.numeric(C0401),
         C0402=as.numeric(C0402),
         C0403=as.numeric(C0403),
         C0404=as.numeric(C0404),
         C0405=as.numeric(C0405),
         C0406=as.numeric(C0406),
         C0407=as.numeric(C0407),
         C0408=as.numeric(C0408),
         C0409=as.numeric(C0409),
         C0410=as.numeric(C0410),
         C0411=as.numeric(C0411),
         C0412=as.numeric(C0412),
         C0413=as.numeric(C0413),
         C0414=as.numeric(C0414),
         C0415=as.numeric(C0415),
         C0416=as.numeric(C0416),
         C0417=as.numeric(C0417),
         C0418=as.numeric(C0418),
         C0419=as.numeric(C0419),
         C0420=as.numeric(C0420),
         C0421=as.numeric(C0421),
         C0422=as.numeric(C0422),
         C0477=as.numeric(case_when(trimws(C0477)=='C04.77'~77)),
         
         C050=factor(case_when(trimws(C050)=='C05.0'~1,TRUE~0),
                         labels = c('Não','Sim')),
         
         #C051=as.numeric(C051),
         C052=as.numeric(C052),
         C053=as.numeric(C053),
         
         C061=factor(str_replace(trimws(C061),'C06.','')),
         
         C062=factor(str_replace(trimws(C062),'C06.','')),
         
         C063=factor(str_replace(trimws(C063),'C06.','')),
         
         C064=factor(str_replace(trimws(C064),'C06.','')),
         
         C065=factor(str_replace(trimws(C065),'C06.','')),
         
         C066=factor(str_replace(trimws(C066),'C06.','')),
         
         C07=factor(case_when(trimws(C07)=='C07.1'~1,
                                  trimws(C07)=='C07.2'~2,
                                  trimws(C07)=='C07.3'~3,
                                  trimws(C07)=='C07.8'~8),
                    labels = c( 'Existem vários na região',
                                'Não tem banco',
                                'Não há bancos suficientes',
                                'Não sabe/não quis responder')),
         
         C08=factor(case_when(trimws(C08)=='C08.1'~1,
                                  trimws(C08)=='C08.2'~2,
                                  trimws(C08)=='C08.3'~3,
                                  trimws(C08)=='C08.4'~4,
                                  trimws(C08)=='C08.8'~8),
                    labels = c( 'Utilizo vários bancos',
                                'Utilizo apenas um banco',
                                'Uso os canais eletrônicos',
                                'Não uso porque considero os serviços/produtos/taxas insatisfatórios', 
                                'Não sabe/não quis responder')),
         
         C09=factor(case_when(trimws(C09)=='C09.01'~01,
                              trimws(C09)=='C09.02'~02,
                              trimws(C09)=='C09.03'~03,
                              trimws(C09)=='C09.04'~04,
                              trimws(C09)=='C09.05'~05,
                              trimws(C09)=='C09.06'~06,
                              trimws(C09)=='C09.07'~07,
                              trimws(C09)=='C09.08'~08,
                              trimws(C09)=='C09.09'~09,
                              trimws(C09)=='C09.88'~88),
                    labels = c( 'Cartão de Crédito',
                                'Financiamento/Empréstimo',
                                'Investimento',
                                'Recebimento de contas',
                                'Seguro',
                                'Previdência',
                                'Canais de atendimento',
                                'Recebimento de salário',
                                'Outros',
                                'Não sabe/não quis responder')),
         
         C101=factor(case_when(trimws(C101)=='C10.1'~1,
                                   trimws(C101)=='C10.2'~2,
                                   trimws(C101)=='C10.3'~3,
                                   trimws(C101)=='C10.4'~4,
                                   trimws(C101)=='C10.5'~5,
                                   trimws(C101)=='C10.6'~6,
                                   trimws(C101)=='C10.7'~7,
                                   trimws(C101)=='C10.8'~8,
                                   trimws(C101)=='C10.9'~9),
                     labels = c( 'Bradesco',
                                 'Banco Regional de Brasília - BRB',
                                 'Banco do Brasil - BB',
                                 'Caixa Econômica Federal - CEF',
                                 'Itaú',
                                 'Santander',
                                 'Outros',
                                 'Não sabe/não quis responder')),
         
         C102=factor(case_when(trimws(C102)=='C10.1'~1,
                                   trimws(C102)=='C10.2'~2,
                                   trimws(C102)=='C10.3'~3,
                                   trimws(C102)=='C10.4'~4,
                                   trimws(C102)=='C10.5'~5,
                                   trimws(C102)=='C10.6'~6,
                                   trimws(C102)=='C10.7'~7,
                                   trimws(C102)=='C10.8'~8,
                                   trimws(C102)=='C10.9'~9),
                     labels = c( 'Bradesco',
                                 'Banco Regional de Brasília - BRB',
                                 'Banco do Brasil - BB',
                                 'Caixa Econômica Federal - CEF',
                                 'Itaú',
                                 'Santander',
                                 'Outros',
                                 'Não sabe/não quis responder')),
         
         C103=factor(case_when(trimws(C103)=='C10.1'~1,
                                   trimws(C103)=='C10.2'~2,
                                   trimws(C103)=='C10.3'~3,
                                   trimws(C103)=='C10.4'~4,
                                   trimws(C103)=='C10.5'~5,
                                   trimws(C103)=='C10.6'~6,
                                   trimws(C103)=='C10.7'~7,
                                   trimws(C103)=='C10.8'~8,
                                   trimws(C103)=='C10.9'~9,
                                   trimws(C103)=='C10.99'~99),
                     labels = c( 'Bradesco',
                                 'Banco Regional de Brasília - BRB',
                                 'Banco do Brasil - BB',
                                 'Caixa Econômica Federal - CEF',
                                 'Itaú',
                                 'Santander',
                                 'Outros',
                                 'Não sabe/não quis responder')),
         
         C104=factor(case_when(trimws(C104)=='C10.1'~1,
                                   trimws(C104)=='C10.2'~2,
                                   trimws(C104)=='C10.3'~3,
                                   trimws(C104)=='C10.4'~4,
                                   trimws(C104)=='C10.5'~5,
                                   trimws(C104)=='C10.6'~6,
                                   trimws(C104)=='C10.7'~7,
                                   trimws(C104)=='C10.8'~8,
                                   trimws(C104)=='C10.9'~9,
                                   trimws(C104)=='C10.99'~99),
                     labels = c( 'Bradesco',
                                 'Banco Regional de Brasília - BRB',
                                 'Banco do Brasil - BB',
                                 'Caixa Econômica Federal - CEF',
                                 'Itaú',
                                 'Safra',
                                 'Santander',
                                 'Outros',
                                 'Não sabe/não quis responder'))
  ) 

#Tratamento dos "Saltos"
domicilio <- domicilio %>% 
  mutate(B04=as.numeric(case_when(as.numeric(B03) %in% c(1,3,4,5,6,7,8,9,10,11,12,13,14,15)~99999,
                                  TRUE~B04)),
         
         B05=as.numeric(case_when(as.numeric(B03) %in% c(1,2,3,4,5,10,11,12,13,14,15)~99999,
                                  B04>=0~99999,
                                  TRUE~B05)),
         
         C09=factor(case_when(as.numeric(C08)==4~99,
                              TRUE~as.numeric(C09)),
                    labels = c( 'Cartão de Crédito',
                                'Financiamento/Empréstimo',
                                'Investimento',
                                'Recebimento de contas',
                                'Seguro',
                                'Previdência',
                                'Canais de atendimento',
                                'Recebimento de salário',
                                'Outros',
                                'Não sabe/não quis responder',
                                'Não se aplica'))
  ) 


table(domicilio$B04,useNA = "ifany")

table(domicilio$C09,useNA = "ifany")


View(domicilio %>% dplyr::filter(is.na(B04)==TRUE))
